import { useEffect, useState, type FormEvent } from 'react';
import { Alert } from '../../components/ui/Alert';
import type { AdminUser } from '../../services/adminApi';
import { managementApi, type ModuleSummary, type TipRecord } from '../../services/managementApi';
import type { Course, Question, Simulation } from '../../types/student';
import { getErrorMessage } from '../../utils/errors';
import styles from './BackofficePage.module.css';

export type AdminResource = 'usuarios' | 'conteudos' | 'questoes' | 'simulados' | 'dicas';
const copy: Record<AdminResource, { eyebrow: string; title: string; subtitle: string }> = {
  usuarios: { eyebrow: 'Gestão de acesso', title: 'Usuários', subtitle: 'Organize perfis, permissões e status de acesso.' },
  conteudos: { eyebrow: 'Biblioteca', title: 'Conteúdos', subtitle: 'Construa a trilha de preparação por cursos, módulos e aulas.' },
  questoes: { eyebrow: 'Banco de questões', title: 'Questões', subtitle: 'Mantenha o treino alinhado ao estilo da prova.' },
  simulados: { eyebrow: 'Avaliações', title: 'Simulados', subtitle: 'Monte experiências completas de prova para os alunos.' },
  dicas: { eyebrow: 'Comunicação', title: 'Dicas do dia', subtitle: 'Publique lembretes curtos que aparecem no estudo.' },
};

export function AdminResourcePage({ resource }: { resource: AdminResource }) {
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [courses, setCourses] = useState<Course[]>([]);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [simulations, setSimulations] = useState<Simulation[]>([]);
  const [tips, setTips] = useState<TipRecord[]>([]);
  const [search, setSearch] = useState('');
  const [expanded, setExpanded] = useState<string | null>(null);
  const [modules, setModules] = useState<Record<string, ModuleSummary[]>>({});
  const [newCourse, setNewCourse] = useState({ title: '', description: '' });
  const [newModule, setNewModule] = useState({ courseId: '', title: '' });
  const [newQuestion, setNewQuestion] = useState({ moduleId: '', subject: '', statement: '', alternatives: ['', '', '', '', ''], correct: '0', examBoard: 'OAB/FGV', year: '', a: '', b: '' });
  const [newSimulation, setNewSimulation] = useState({ title: '', description: '', timeLimitMinutes: '120', questionIds: '' });
  const [newTip, setNewTip] = useState({ title: '', content: '', category: '' });

  useEffect(() => {
    setLoading(true); setError(null);
    const request = resource === 'usuarios' ? managementApi.listUsers(search).then((result) => setUsers(result.rows)) : resource === 'conteudos' ? managementApi.listCourses().then(setCourses) : resource === 'questoes' ? managementApi.listQuestions().then((result) => setQuestions(result.rows)) : resource === 'simulados' ? managementApi.listSimulations().then(setSimulations) : managementApi.listTips().then(setTips);
    request.catch((reason) => setError(getErrorMessage(reason, 'Não foi possível carregar esta tela.'))).finally(() => setLoading(false));
  }, [resource, search]);

  async function act(action: () => Promise<unknown>, refresh = true) { try { setError(null); await action(); if (refresh) window.location.reload(); } catch (reason) { setError(getErrorMessage(reason, 'Não foi possível concluir esta ação.')); } }
  async function toggleCourse(course: Course) { await act(() => managementApi.updateCourse(course.id, { status: course.status === 'PUBLICADO' ? 'RASCUNHO' : 'PUBLICADO' })); }
  async function toggleTip(tip: TipRecord) { await act(() => managementApi.updateTip(tip.id, { active: !tip.active })); }
  async function submitCourse(event: FormEvent) { event.preventDefault(); if (!newCourse.title.trim()) return; await act(() => managementApi.createCourse({ ...newCourse, status: 'RASCUNHO' })); }
  async function submitModule(event: FormEvent) { event.preventDefault(); if (!newModule.courseId || !newModule.title.trim()) return; await act(() => managementApi.createModule(newModule)); }
  async function submitQuestion(event: FormEvent) { event.preventDefault(); if (!newQuestion.moduleId || !newQuestion.statement || !newQuestion.subject || newQuestion.alternatives.some((alternative) => !alternative.trim())) return; await act(() => managementApi.createQuestion({ moduleId: newQuestion.moduleId, statement: newQuestion.statement, subject: newQuestion.subject, examBoard: newQuestion.examBoard.trim() || undefined, year: newQuestion.year ? Number(newQuestion.year) : undefined, alternatives: newQuestion.alternatives.map((text, order) => ({ text: text.trim(), order, correct: String(order) === newQuestion.correct })) })); }
  async function submitSimulation(event: FormEvent) { event.preventDefault(); const questionIds = newSimulation.questionIds.split(',').map((id) => id.trim()).filter(Boolean); if (!newSimulation.title || !questionIds.length) return; await act(() => managementApi.createSimulation({ title: newSimulation.title, description: newSimulation.description, timeLimitMinutes: Number(newSimulation.timeLimitMinutes), questionCount: questionIds.length, questionIds })); }
  async function submitTip(event: FormEvent) { event.preventDefault(); if (!newTip.title || !newTip.content) return; await act(() => managementApi.createTip(newTip)); }
  async function toggleCourseDetails(courseId: string) { if (expanded === courseId) return setExpanded(null); if (!modules[courseId]) { const result = await managementApi.listModules(courseId).catch(() => []); setModules((current) => ({ ...current, [courseId]: result })); } setExpanded(courseId); }

  if (resource === 'questoes' && !loading) return <div className={styles.page}><p className={styles.eyebrow}>Banco de questões</p><h1 className={styles.heading}>Questões</h1><p className={styles.intro}>Cadastre questões objetivas com cinco alternativas, inclusive de provas anteriores da OAB.</p>{error && <div className={styles.error}><Alert type="error">{error}</Alert></div>}<section className={styles.panel}><h2 className={styles.panelTitle}>Nova questão</h2><form className={styles.form} onSubmit={submitQuestion}><label className={styles.field}>ID do módulo<input className={styles.input} value={newQuestion.moduleId} onChange={(e) => setNewQuestion({ ...newQuestion, moduleId: e.target.value })} /></label><label className={styles.field}>Disciplina<input className={styles.input} value={newQuestion.subject} onChange={(e) => setNewQuestion({ ...newQuestion, subject: e.target.value })} /></label><label className={styles.field}>Enunciado<textarea className={styles.textarea} value={newQuestion.statement} onChange={(e) => setNewQuestion({ ...newQuestion, statement: e.target.value })} /></label><div className={styles.formGrid}>{newQuestion.alternatives.map((alternative, index) => <label className={styles.field} key={index}>Alternativa {String.fromCharCode(65 + index)}<input className={styles.input} value={alternative} onChange={(e) => setNewQuestion({ ...newQuestion, alternatives: newQuestion.alternatives.map((current, alternativeIndex) => alternativeIndex === index ? e.target.value : current) })} /></label>)}</div><div className={styles.formGrid}><label className={styles.field}>Origem da prova<input className={styles.input} value={newQuestion.examBoard} onChange={(e) => setNewQuestion({ ...newQuestion, examBoard: e.target.value })} /></label><label className={styles.field}>Ano da prova<input className={styles.input} type="number" value={newQuestion.year} onChange={(e) => setNewQuestion({ ...newQuestion, year: e.target.value })} /></label></div><label className={styles.field}>Resposta correta<select className={styles.select} value={newQuestion.correct} onChange={(e) => setNewQuestion({ ...newQuestion, correct: e.target.value })}>{newQuestion.alternatives.map((_, index) => <option value={index} key={index}>Alternativa {String.fromCharCode(65 + index)}</option>)}</select></label><button className={styles.primaryButton}>Adicionar questão</button></form><div className={styles.list}>{questions.map((question) => <div className={styles.listRow} key={question.id}><div><p className={styles.rowTitle}>{question.subject}</p><p className={styles.rowMeta}>{question.statement}</p></div><button className={styles.dangerButton} onClick={() => act(() => managementApi.removeQuestion(question.id))}>Excluir</button></div>)}</div></section></div>;

  const heading = copy[resource];
  return <div className={styles.page}><p className={styles.eyebrow}>{heading.eyebrow}</p><h1 className={styles.heading}>{heading.title}</h1><p className={styles.intro}>{heading.subtitle}</p>{error && <div className={styles.error}><Alert type="error">{error}</Alert></div>}{loading ? <div className={styles.panel}><div className={styles.empty}>Carregando dados...</div></div> : <>
    {resource === 'usuarios' && <section className={styles.panel}><div className={styles.panelHeader}><div><h2 className={styles.panelTitle}>Base de usuários</h2><p className={styles.panelMeta}>{users.length} resultados nesta busca</p></div><input className={styles.search} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar nome ou email" /></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Usuário</th><th>Perfil</th><th>Plano</th><th>Aprovação</th><th>Status</th><th>Último acesso</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><div className={styles.person}><strong>{user.name}</strong><span>{user.email}</span></div></td><td>{user.role}</td><td>{user.subscriptionPlan === 'VITALICIO' ? 'Vitalício' : user.subscriptionPlan === 'BASICO' ? 'Básico' : 'Sem plano'}</td><td><span className={`${styles.badge} ${user.approved ? styles.activeBadge : styles.inactiveBadge}`}>{user.approved ? 'Aprovado' : 'Pendente'}</span></td><td><span className={`${styles.badge} ${user.status === 'ATIVO' ? styles.activeBadge : styles.inactiveBadge}`}>{user.status}</span></td><td>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleDateString('pt-BR') : 'Nunca'}</td></tr>)}</tbody></table></div></section>}
    {resource === 'conteudos' && <><section className={styles.panel}><h2 className={styles.panelTitle}>Novo curso</h2><form className={styles.form} onSubmit={submitCourse}><div className={styles.formGrid}><label className={styles.field}>Título<input className={styles.input} value={newCourse.title} onChange={(e) => setNewCourse({ ...newCourse, title: e.target.value })} /></label><label className={styles.field}>Descrição<input className={styles.input} value={newCourse.description} onChange={(e) => setNewCourse({ ...newCourse, description: e.target.value })} /></label></div><button className={styles.primaryButton}>Criar rascunho</button></form><div className={styles.list}>{courses.map((course) => <div key={course.id}><div className={styles.listRow}><div><p className={styles.rowTitle}>{course.title}</p><p className={styles.rowMeta}>{course.description || 'Sem descrição'}</p></div><div className={styles.actions}><span className={`${styles.badge} ${course.status === 'PUBLICADO' ? styles.activeBadge : styles.inactiveBadge}`}>{course.status}</span><button className={styles.linkButton} onClick={() => toggleCourseDetails(course.id)}>{expanded === course.id ? 'Fechar' : 'Módulos'}</button><button className={styles.linkButton} onClick={() => toggleCourse(course)}>{course.status === 'PUBLICADO' ? 'Despublicar' : 'Publicar'}</button><button className={styles.dangerButton} onClick={() => act(() => managementApi.removeCourse(course.id))}>Excluir</button></div></div>{expanded === course.id && <div className={styles.sublist}>{(modules[course.id] || []).map((module) => <div className={styles.subitem} key={module.id}><strong>{module.title}</strong> · {module.totalContents} conteúdos</div>)}{(modules[course.id] || []).length === 0 && <div className={styles.subitem}>Nenhum módulo cadastrado.</div>}</div>}</div>)}</div></section><section className={styles.panel} style={{ marginTop: 18 }}><h2 className={styles.panelTitle}>Adicionar módulo</h2><form className={styles.form} onSubmit={submitModule}><div className={styles.formGrid}><label className={styles.field}>Curso<select className={styles.select} value={newModule.courseId} onChange={(e) => setNewModule({ ...newModule, courseId: e.target.value })}><option value="">Selecione um curso</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label><label className={styles.field}>Título<input className={styles.input} value={newModule.title} onChange={(e) => setNewModule({ ...newModule, title: e.target.value })} /></label></div><button className={styles.primaryButton}>Adicionar módulo</button></form></section></>}
    {resource === 'questoes' && <section className={styles.panel}><h2 className={styles.panelTitle}>Nova questão</h2><form className={styles.form} onSubmit={submitQuestion}><div className={styles.formGrid}><label className={styles.field}>ID do módulo<input className={styles.input} value={newQuestion.moduleId} onChange={(e) => setNewQuestion({ ...newQuestion, moduleId: e.target.value })} /></label><label className={styles.field}>Disciplina<input className={styles.input} value={newQuestion.subject} onChange={(e) => setNewQuestion({ ...newQuestion, subject: e.target.value })} /></label></div><label className={styles.field}>Enunciado<textarea className={styles.textarea} value={newQuestion.statement} onChange={(e) => setNewQuestion({ ...newQuestion, statement: e.target.value })} /></label><div className={styles.formGrid}><label className={styles.field}>Alternativa A<input className={styles.input} value={newQuestion.a} onChange={(e) => setNewQuestion({ ...newQuestion, a: e.target.value })} /></label><label className={styles.field}>Alternativa B<input className={styles.input} value={newQuestion.b} onChange={(e) => setNewQuestion({ ...newQuestion, b: e.target.value })} /></label></div><label className={styles.field}>Resposta correta<select className={styles.select} value={newQuestion.correct} onChange={(e) => setNewQuestion({ ...newQuestion, correct: e.target.value })}><option value="0">A</option><option value="1">B</option></select></label><button className={styles.primaryButton}>Adicionar questão</button></form><div className={styles.list}>{questions.map((question) => <div className={styles.listRow} key={question.id}><div><p className={styles.rowTitle}>{question.subject}</p><p className={styles.rowMeta}>{question.statement}</p></div><button className={styles.dangerButton} onClick={() => act(() => managementApi.removeQuestion(question.id))}>Excluir</button></div>)}</div></section>}
    {resource === 'simulados' && <section className={styles.panel}><h2 className={styles.panelTitle}>Novo simulado</h2><form className={styles.form} onSubmit={submitSimulation}><div className={styles.formGrid}><label className={styles.field}>Título<input className={styles.input} value={newSimulation.title} onChange={(e) => setNewSimulation({ ...newSimulation, title: e.target.value })} /></label><label className={styles.field}>Tempo em minutos<input className={styles.input} type="number" value={newSimulation.timeLimitMinutes} onChange={(e) => setNewSimulation({ ...newSimulation, timeLimitMinutes: e.target.value })} /></label></div><label className={styles.field}>Descrição<input className={styles.input} value={newSimulation.description} onChange={(e) => setNewSimulation({ ...newSimulation, description: e.target.value })} /></label><label className={styles.field}>IDs das questões, separados por vírgula<input className={styles.input} value={newSimulation.questionIds} onChange={(e) => setNewSimulation({ ...newSimulation, questionIds: e.target.value })} /></label><button className={styles.primaryButton}>Criar simulado</button></form><div className={styles.list}>{simulations.map((simulation) => <div className={styles.listRow} key={simulation.id}><div><p className={styles.rowTitle}>{simulation.title}</p><p className={styles.rowMeta}>{simulation.questionCount} questões · {simulation.timeLimitMinutes} minutos</p></div><button className={styles.dangerButton} onClick={() => act(() => managementApi.removeSimulation(simulation.id))}>Excluir</button></div>)}</div></section>}
    {resource === 'dicas' && <section className={styles.panel}><h2 className={styles.panelTitle}>Nova dica</h2><form className={styles.form} onSubmit={submitTip}><label className={styles.field}>Título<input className={styles.input} value={newTip.title} onChange={(e) => setNewTip({ ...newTip, title: e.target.value })} /></label><label className={styles.field}>Mensagem<textarea className={styles.textarea} value={newTip.content} onChange={(e) => setNewTip({ ...newTip, content: e.target.value })} /></label><label className={styles.field}>Categoria<input className={styles.input} value={newTip.category} onChange={(e) => setNewTip({ ...newTip, category: e.target.value })} /></label><button className={styles.primaryButton}>Publicar dica</button></form><div className={styles.list}>{tips.map((tip) => <div className={styles.listRow} key={tip.id}><div><p className={styles.rowTitle}>{tip.title}</p><p className={styles.rowMeta}>{tip.content}</p></div><div className={styles.actions}><span className={`${styles.badge} ${tip.active ? styles.activeBadge : styles.inactiveBadge}`}>{tip.active ? 'Ativa' : 'Inativa'}</span><button className={styles.linkButton} onClick={() => toggleTip(tip)}>{tip.active ? 'Desativar' : 'Ativar'}</button><button className={styles.dangerButton} onClick={() => act(() => managementApi.removeTip(tip.id))}>Excluir</button></div></div>)}</div></section>}
  </>}</div>;
}